// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "retoRimacV1",
    "version": "1"
  },
  "paths": {
    "/fusionados": {
      "get": {
        "summary": "fusionados",
        "description": "",
        "tags": [
          "Fusionados"
        ],
        "operationId": "fusionados.get./fusionados",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/almacenar": {
      "post": {
        "summary": "almacenar",
        "description": "",
        "operationId": "almacenar.post./almacenar",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/historial": {
      "get": {
        "summary": "historial",
        "description": "",
        "operationId": "historial.get./historial",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Pokemon": {
      "properties": {
        "name": {
          "title": "Pokemon.name",
          "type": "string"
        },
        "url": {
          "title": "Pokemon.url",
          "type": "string"
        }
      },
      "required": [
        "name",
        "url"
      ],
      "additionalProperties": false,
      "title": "Pokemon",
      "type": "object"
    },
    "EntrenadorConPokemones": {
      "properties": {
        "Id": {
          "title": "EntrenadorConPokemones.Id",
          "type": "string"
        },
        "name": {
          "title": "EntrenadorConPokemones.name",
          "type": "string"
        },
        "pokemones": {
          "items": {
            "$ref": "#/definitions/Pokemon",
            "title": "EntrenadorConPokemones.pokemones.[]"
          },
          "title": "EntrenadorConPokemones.pokemones",
          "type": "array"
        }
      },
      "required": [
        "Id",
        "name",
        "pokemones"
      ],
      "additionalProperties": false,
      "title": "EntrenadorConPokemones",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/"
};